repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: double-quote-string-fixer

- repo: https://github.com/python-poetry/poetry
  rev: '1.5.1'
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "./ugc/requirements.txt", "--without-hashes"]
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "./tests/functional/requirements.txt", "--without-hashes", "--only", "test"]
