[tool.ruff]
select = ['ANN', 'ARG', 'B', 'BLE', 'C40', 'COM', 'DJ', 'DTZ', 'E', 'EM', 'ERA001', 'EXE', 'F', 'FBT', 'G', 'I', 'ICN', 'INP', 'ISC', 'N', 'PIE', 'PL', 'PT', 'PYI', 'Q', 'RET', 'RSE', 'S', 'SIM', 'SLF', 'T20', 'TRY', 'W', 'YTT', 'UP']
ignore = ['ANN101', 'ANN102', 'COM812']
show-fixes = true
line-length = 88
src = ['ugc/src', 'tests/functional']

[tool.ruff.per-file-ignores]
'ugc/src/main.py' = ['S104']
'ugc/src/exceptions/base.py' = ['ANN001', 'ANN204']
'ugc/src/repositories/abstract/repository.py' = ['ANN002', 'ANN003', 'ANN401']
'tests*' = ['S101', 'PLR0913', 'ANN']

[tool.ruff.flake8-bugbear]
extend-immutable-calls = [
  'fastapi.Depends',
  'fastapi.params.Depends',
  'fastapi.Query',
  'fastapi.params.Query',
  'fastapi.Cookie',
  'fastapi.params.Cookie',
  'fastapi.Body',
  'fastapi.params.Body',
]

[tool.ruff.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.mypy]
mypy_path = 'ugc/src'
ignore_missing_imports = true
explicit_package_bases = true
namespace_packages = true

[tool.black]
line-length = 88
target-version = ['py310', 'py311']
skip-string-normalization = true

[tool.isort]
profile = 'black'
src_paths = ['ugc/src', 'tests/functional']
multi_line_output = 3
line_length = 88
