name: UGC CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy black isort lxml
        pip install -r ugc/requirements.txt

    - name: Check code formatting by black
      run: |
        black . --check

    - name: Check by isort util
      run: |
        isort . --check

    - name: Analysing the code with ruff
      run: |
        ruff .

    - name: Analysing the code with mypy
      run: |
        mypy .

  tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/functional/requirements.txt
        make install

    - name: Test with pytest
      run: make test
